#手机号、密码
mobileNo: 158XXXX
password: *****
hospitalName: 301医院
#医院的科室id
departmentId: 200002273
#  预约日期，只需要改前面的日期，后面的时间不用改，保留现在的默认值（yml解析时间用的是iso8601标准）
bookDate: 2019-07-24T00:00:00+08:00
#就诊人姓名，一个账户里可能有多个就诊人
name: 张三
#以下为医生号源选择依据，二选一，如果同时都填写了，以 dutySourceId 优先，如果不知道 dutySourceId ，一定要留为空
#值班id，在捡漏时可以通过接口查看id，如果是抢票则没办法了。
#  dutySourceId可以唯一确定值班的医生
dutySourceId:
#医生姓名，这个适合抢票模式，在提前知道要挂哪个医生的号的前提下使用，但是也有问题：医生有重名的，医生同一天中有上下午都值班的，则会有重复
doctorName: 普通口腔外科
#医生的值班时间，三个选择：上午、下午、晚上
dutyTime: 下午

#注入值前面必须有空格，后面带空格不要紧，会被自动处理去掉